baseurl = "https://vw4htrains.club"
title = "4H Model Railroad club"
languageCode = "en"
DefaultContentLanguage = "en"
paginate = "5" # Number of posts per page
theme = ["hugo-dpsg", "hugo-snap-gallery"]

[Author] # Used in authorbox
  #name = "Scout Master"
  #bio = "The Scout Master is the leader of this local scout group"
  #avatar = "img/avatar.png"

[Params]
  description = "Welcome to our Model Railroad group!" # Site description. Used in meta description
  copyright = "Van Wert 4H Model Railroad Club" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = false # Show pager navigation (prev/next links) at the bottom of pages if true
  indexPager = true # Show pager navigation on index page
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "01-02-2006" # Change the format of dates
  photosSections = ["Photographs"] # Specify section pages to show on home page and the "Recent photos" widget
  photoTag = "Photographs" # Specify one tag to show on home page and the "Recent photos" widget. Similar as photoSections, but with 1 tag instead of 1 or multiple sections

[Params.style.vars]
  highlightColor = "#339966" # Override main theme color

[Params.logo]
  image = "img/logo2.png" # Logo image. Path relative to "static"
#  header = "img/header.jpg" # Header image. Path relative to "static"
#  header = "img/banner.jpg" # Header image. Path relative to "static"
  title = "Van Wert 4H Model Railroad Club" # Logo title, otherwise will use site title
  subtitle = "All aboard on the railroad!" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["sidemenu" ,"recent", "recent_photos_tags", "social"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  #widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages", "side"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.footer]
  #text = "[Imprint and Privacy](/imprint)" # Extra text in footer row, understands markdown
  #right = "Donate!" # Right-aligned text in footer row, understands markdown

[[Params.widgets.social.custom]]
  title = "Van Wert 4H Facebook"
  url = "https://www.facebook.com/vanwert4h"
  icon = "svg/facebook.svg" # Optional. Path relative to "layouts/partials"

  [[Params.widgets.social.custom]]
  title = "Van Wert 4H Office"
  url = "https://vanwert.osu.edu/"
  #icon = "svg/facebook.svg" # Optional. Path relative to "layouts/partials"

  [[Params.widgets.social.custom]]
  title = "Van Wert County Fair"
  url = "https://www.vanwertcountyfair.com/"
  #icon = "svg/facebook.svg" # Optional. Path relative to "layouts/partials"

  [[Params.widgets.social.custom]]
  title = "Upcoming Train Events"
  url = "/other-events/"
  #icon = "svg/facebook.svg" # Optional. Path relative to "layouts/partials"


# Custom menu items, normally controlled via front matter in /content files
[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "Meeting-Dates"
    name = "Meetings"
    url = "/meeting-dates/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "reminders"
    name = "Text Reminders"
    url = "/Text-Reminders/"
    weight = 5

    [[menu.main]]
    identifier = "Leaders"
    name = "Leaders"
    url = "/Leaders/"
    weight = 4